### ISSUE TITLE
Problems linking/including QDMI in a FoMaC

### ISSUE THREAD

**Issue by Durganshu** [Munich-Quantum-Software-Stack/QDMI#105]
Hi!

I have been trying to use the latest QDMI version (on develop branch) with sys-sage (as a FoMaC). I installed qdmi in my linux system and my `/usr/local/include/` looks as follows:

```
$> ls /usr/local/include/qdmi/
client  client.h  common  device  device.h  driver  driver.h
```

I noticed that qdmi doesn't exports any library (no `lqdmi.so` in my `/usr/local/lib/`).

What should be the best way to use QDMI with my repository?

I modified my CMakeLists.txt to include this (I hardcoded the path, though I know there are better ways of doing that):
`target_include_directories(sys-sage PRIVATE /usr/local/include/qdmi)`

I used the functions defined in `example_fomac.cpp`  for reference and initial testing. I still get some linker errors:

```
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to QDMI_query_get_sites'
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to QDMI_query_get_operations'
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to QDMI_query_device_property'
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to QDMI_query_operation_property'
```

Did I miss any step while building/installing QDMI?

**Comment by ystade** [comment]
Hi @Durganshu, 
Please note that QDMI (nowadays) is a header-only library. Hence, the observed header files in the include directory look alright. From the text above, I cannot see how you included QDMI. However, the usual way to include it via `find_package(qdmi)`. If you installed qdmi not in the normal search path of CMake and CMake does not find it, you can specify the custom install directory by setting the variable `CMAKE_PREFIX_PATH` accordingly. In order to link QDMI with your library you should the use `target_link_libraries`. There should be no need for using `target_include_directories`. 

I hope, I could help you. If you have more questions, please do not hesitate to ask them. I order to provide better help, a minimal working example is highly appreciated.

**Comment by ystade** [comment]
Additionally, you can only test a QDMI client together with a driver implementation that usually uses at least one device implementation. For inspiration, please take a look at the examples in the QDMI repository.

**Comment by Durganshu** [comment]
Thanks, @ystade, for your replies.

QDMI is already in the path, and cmake can find it. My CMakeLists looks like this:
```
add_library(sys-sage SHARED ${SOURCES} ${HEADERS})

find_package(qdmi)
target_link_libraries(sys-sage PRIVATE qdmi::qdmi)
```
You can also see the complete CMakeLists here: https://github.com/Durganshu/sys-sage/blob/694e938a8b466b5f73f8c5a0348c31ff549f3094/src/CMakeLists.txt#L39

Some outputs that might be useful:

```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_QDMI_DOCS=OFF
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.14")
-- Found qdmi version 1.0.0
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Configuring done (3.4s)
-- Generating done (0.0s)
```

```
$ make -j4
[ 41%] Built target sys-sage
[ 44%] Linking CXX executable basic_usage
[ 51%] Building CXX object examples/CMakeFiles/custom_attributes.dir/custom_attributes.cpp.o
[ 51%] Building CXX object examples/CMakeFiles/larger_topo.dir/larger_topo.cpp.o
[ 55%] Building CXX object examples/CMakeFiles/mt4g-parser.dir/mt4g-parser.cpp.o
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to `QDMI_query_get_sites'
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to `QDMI_query_get_operations'
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to `QDMI_query_device_property'
/usr/bin/ld: ../src/libsys-sage.so: undefined reference to `QDMI_query_operation_property'
collect2: error: ld returned 1 exit status
```

**Comment by ystade** [comment]
Ok, I think, I found it. The building of the library just works fine. The problem is when you build the executables in the examples directory, the the compiler actually requires an implementation of all functions that are called. And here arises the previously mentioned problem: in order to provide those implementations you need to link a QDMI driver. You may want to take the example driver from QDMI. However, then you also need a QDMI device that you can load, which you also may want to take from the QDMI examples.

**Comment by Durganshu** [comment]
Hi @ystade!

Thanks for your suggestions. I tried your solution and it worked!!!

However, there's still some manual stuff that needs to be done. QDMI doesn't install the `example_fomac`, `example_driver` and  `example_client` by default to the default LD paths (/usr/local/lib). So, the LD_LIBRARY_PATH needs to be manually specified to let cmake find them. Was this intentional or maybe an oversight?

In any case, thanks for your solution. I can now proceed with the FoMac implementation.

**Comment by ystade** [comment]
As all of these targets refer to examples that are just meant to showcase the usage of QDMI, they were never thought to be installed. So everything is correct here.
